{ lib, basePath, config, configWorkspace }:
let
  escaped = builtins.replaceStrings [ "." ] [ "_" ];
  processConfigItem = jsPath: path: workspaceOnly: value:
    let fieldPath = "${jsPath}.${escaped value.name}";
    in if value.type == "section" then
      "\n    ${fieldPath} = {};"
      + (processConfigItems fieldPath "${path}.${value.name}" workspaceOnly value.children)
    else
      "\n    ${fieldPath} = new ConfigItem(\"${path}.${value.name}\", ${workspaceOnly});";
  processConfigItems = jsPath: path: workspaceOnly: items:
    lib.concatStrings
    (builtins.map (processConfigItem jsPath path workspaceOnly) items);
in ''
  // autogenerated by nova-extension-utils

  const ConfigItem = require("config-item.js").ConfigItem;

  class Config {
    constructor() {${processConfigItems "this" basePath "false" config}${processConfigItems "this" basePath "true" configWorkspace}
    }
  }

  exports.Config = Config;
''
