{
  lib,
  basePath,
  config
}: let
  escaped = builtins.replaceStrings ["."] ["_"];
  processConfigItem = name: value: if
    value.type == "section"
  then
    processConfigItems value.children
  else let
    field = escaped name;
  in "\n    this.${field} = new ConfigItem(\"${basePath + "." + name}\");";
  processConfigItems = items: lib.concatStrings (
    lib.mapAttrsToList processConfigItem items
  );
in ''
// autogenerated by nova-extension-utils

const ConfigItem = require("config-item.js").ConfigItem;

class Config {
  constructor() {${processConfigItems config}
  }
}

exports.Config = Config;
''