// this library is provided by nova-extension-utils
const LanguageServer = require("language-server.js").LanguageServer;
// this has been autogenerated from the config value in your flake.nix
const Config = require("config.js").Config;

let langserver = null;
let config = null;

exports.activate = () => {
  config = new Config();
  langserver = new LanguageServer(
    // internal identifier. the client will have the id org.example.myLanguage.client
    "org.example.myLanguage",
    // serverOptions as defined in the docs for LanguageClient
    { syntaxes: ["myLanguage"] },
    // this configuration item has been autogenerated from flake.nix.
    // it lets the user set a default language server in the extension's settings,
    // and override it per workspace if necessary.
    config.languageServer
  );
};

exports.deactivate = () => {
  langserver.stop();
  langserver = null;
};